Add std headers when running SortChecker in wrapper.

diff --git a/scripts/cc b/scripts/cc
--- a/scripts/cc
+++ b/scripts/cc
@@ -1,9 +1,9 @@
 #!/bin/sh
 
 # The MIT License (MIT)
-# 
+#▫
 # Copyright (c) 2022 Yury Gribov
-# 
+#▫
 # Use of this source code is governed by The MIT License (MIT)
 # that can be found in the LICENSE.txt file.
 
@@ -11,9 +11,11 @@ set -eu
 #set -x
 
 if echo "$0" | grep -q ++; then
-  exe=g++
+  real_exe=g++
+  type=c++
 else
-  exe=gcc
+  real_exe=gcc
+  type=c
 fi
 
 ROOT=$(dirname $0)/..
@@ -23,8 +25,14 @@ FILES=$(echo "$@" | grep -o '[^ ]\+\.\(cc\|cpp\|c\|cxx\|C\)\( \|$\)' || true)
 OPTS=$(echo "$@" | sed -e 's/[^ ]\+\.\(cc\|cpp\|c\|cxx\|C\)\( \|$\)//g')
 
 if test -n "$FILES" && ! (echo -- "$OPTS" | grep -q -- '-E\>'); then
-  # Strip unhandled flags
-  OPTS=$(echo $OPTS | sed -e 's/-f\(lifetime-dse\|abi-version\|var-tracking\)[^ ]\+//g')
-  $ROOT/bin/SortChecker --ignore-parse-errors $FILES -- $OPTS -w -fpermissive -Wno-error
+  # Strip unhandled flags (-flto=jobserver causes clang to malfunction)
+  OPTS=$(echo $OPTS | sed -e 's/-f\(lifetime-dse\|abi-version\|var-tracking\|lto\)[^ ]\+//g')
+  # Add std includes
+  INCLUDES=$(clang -x $type -E -Wp,-v /dev/null 2>&1 | awk '/^ \//{ORS=" "; print "-I" $1}')
+  # Disable all warnings
+  WARNS='-fpermissive -w -Wno-everything -Wno-error'
+  if ! $ROOT/bin/SortChecker $FILES -- $OPTS -I$ROOT/include $INCLUDES $WARNS; then
+    echo "SortChecker: failed to compile $FILES"
+  fi
 fi
-/usr/bin/$exe "$@" -I$ROOT/include
+/usr/bin/$real_exe "$@" -I$ROOT/include
